"""Market regime detection and classification.

Financial markets alternate between distinct regimes -- bull/bear,
high/low volatility, risk-on/risk-off -- and strategies that ignore
regime shifts suffer from unstable parameter estimates, false signals,
and tail-risk blow-ups. This module provides tools to detect, classify,
and exploit these structural breaks.

Key concepts
------------
A *regime* is a persistent state of the market characterised by a
distinct set of statistical properties (mean return, volatility,
correlation structure).  Regime detection asks: "which state are we in
right now?" and "when did the last switch occur?"

Model families
--------------
1. **Hidden Markov Models (HMM)** -- the workhorse for regime detection.
   The observable returns are generated by an unobserved Markov chain
   that switches between K states, each with its own emission
   distribution (typically Gaussian).

   - ``fit_hmm`` -- general-purpose HMM fitting via the Baum-Welch
     (EM) algorithm.  Returns transition matrix, emission parameters,
     and the Viterbi state sequence.
   - ``fit_gaussian_hmm`` -- convenience wrapper that fits a Gaussian
     HMM and returns regime means, variances, and transition
     probabilities.  Start here for equity return regimes.
   - ``predict_regime`` -- classify new observations into regimes
     using a fitted HMM.
   - ``rolling_regime_probability`` -- compute time-varying posterior
     probability of being in each regime (useful for blending
     strategies across regimes).

   When to use: you believe the market switches between a small number
   of states (2-4) and want to infer the current state and its
   transition dynamics.

2. **Markov-switching regression** -- extends HMMs by allowing the
   parameters of a regression model (e.g., factor loadings) to change
   with the regime.

   - ``fit_ms_regression`` -- Hamilton-style Markov-switching model
     where both intercept and slope coefficients are regime-dependent.

   When to use: you want regime-dependent factor exposures (e.g., a
   fund's beta is 0.3 in calm markets and 1.5 in crises).

3. **Gaussian mixture regimes** -- simpler alternative to HMM when you
   do not need the sequential (time-dependent) transition structure.
   Clusters returns by their distributional shape.

   - ``gaussian_mixture_regimes`` -- fit a Gaussian Mixture Model
     and label each observation by its most likely component.

   When to use: quick regime labeling for cross-sectional analysis
   or when the Markov assumption is too restrictive.

4. **Kalman filtering and smoothing** -- optimal linear state-space
   estimation.  The Kalman filter is the continuous-state analog of
   the HMM (which is discrete-state).

   - ``kalman_filter`` -- one-pass forward filter: produces filtered
     state estimates (best estimate given data up to time t).
   - ``kalman_smoother`` -- two-pass (Rauch-Tung-Striebel) smoother:
     produces smoothed estimates using the full sample (better for
     ex-post analysis).
   - ``kalman_regression`` -- time-varying coefficient regression via
     Kalman filter.  Use to track evolving betas, hedge ratios, or
     spread means.
   - ``unscented_kalman`` -- handles nonlinear state dynamics via the
     Unscented Transform.  Use when the state transition or
     observation function is nonlinear.

   When to use: you have a state-space model with continuous latent
   states (e.g., time-varying beta, mean-reverting spread level).

5. **Change-point detection** -- finds abrupt structural breaks.

   - ``online_changepoint`` -- Bayesian online change-point detection
     (Adams & MacKay 2007).  Provides a run-length posterior that
     quantifies how likely it is that a change occurred at each point.

   When to use: you need real-time alerts for structural breaks
   (e.g., volatility regime shift, correlation breakdown).

6. **Regime labeling** -- rule-based classification for backtesting.

   - ``label_regimes`` -- label historical periods as bull/bear/flat
     using moving-average crossover or drawdown rules.

7. **Third-party integrations** -- wrappers around specialised
   libraries (``pomegranate``, ``filterpy``, ``river``, ``dynamax``).

   - ``pomegranate_hmm`` -- GPU-accelerated HMM via pomegranate.
   - ``filterpy_kalman`` -- battle-tested Kalman filter via filterpy.
   - ``river_drift_detector`` -- streaming concept-drift detection.
   - ``dynamax_lgssm`` -- JAX-based linear Gaussian state-space model.

Regime-aware investing
----------------------
Once regimes are identified, they can drive portfolio decisions:

- **Regime-conditional allocation**: hold equities in bull regimes,
  shift to bonds or cash in bear regimes.  See ``regime_aware_portfolio``.
- **Regime-filtered signals**: only take long signals when the HMM
  assigns >60% probability to the bull state.
- **Regime statistics**: compute return/vol/Sharpe within each regime
  via ``regime_statistics`` and ``regime_transition_analysis``.

How to choose
-------------
- For 2-3 state equity regime detection: ``fit_gaussian_hmm``.
- For time-varying factor betas: ``kalman_regression``.
- For real-time break detection: ``online_changepoint``.
- For simple backtesting labels: ``label_regimes``.

References
----------
- Hamilton (1989), "A new approach to the economic analysis of
  nonstationary time series and the business cycle"
- Kim & Nelson (1999), "State-Space Models with Regime Switching"
- Adams & MacKay (2007), "Bayesian Online Changepoint Detection"
"""

from wraquant.regimes.base import (
    RegimeDetector,
    RegimeResult,
    detect_regimes,
    regime_report,
)
from wraquant.regimes.changepoint import online_changepoint
from wraquant.regimes.hmm import (
    fit_gaussian_hmm,
    fit_hmm,
    fit_ms_autoregression,
    fit_ms_regression,
    fit_multivariate_hmm,
    gaussian_mixture_regimes,
    predict_regime,
    regime_aware_portfolio,
    regime_conditional_moments,
    regime_statistics,
    regime_transition_analysis,
    rolling_regime_probability,
    select_n_states,
)
from wraquant.regimes.integrations import (
    dynamax_lgssm,
    filterpy_kalman,
    pomegranate_hmm,
    river_drift_detector,
)
from wraquant.regimes.kalman import (
    kalman_filter,
    kalman_regression,
    kalman_smoother,
    unscented_kalman,
)
from wraquant.regimes.labels import label_regimes

__all__ = [
    # base (unified interface)
    "RegimeResult",
    "RegimeDetector",
    "detect_regimes",
    "regime_report",
    # hmm
    "fit_gaussian_hmm",
    "fit_hmm",
    "fit_ms_autoregression",
    "fit_ms_regression",
    "fit_multivariate_hmm",
    "gaussian_mixture_regimes",
    "predict_regime",
    "regime_aware_portfolio",
    "regime_conditional_moments",
    "regime_statistics",
    "regime_transition_analysis",
    "rolling_regime_probability",
    "select_n_states",
    # kalman
    "kalman_filter",
    "kalman_smoother",
    "kalman_regression",
    "unscented_kalman",
    # changepoint
    "online_changepoint",
    # labels
    "label_regimes",
    # integrations
    "pomegranate_hmm",
    "filterpy_kalman",
    "river_drift_detector",
    "dynamax_lgssm",
]
