"""Hidden Markov Model and mixture-model regime detection.

This module provides production-quality regime detection for financial
time series using Gaussian Hidden Markov Models (HMMs), Markov-switching
models, and Gaussian mixture models (GMMs).

**When to use each model:**

- **Gaussian HMM** (``fit_gaussian_hmm``): The workhorse. Models returns as
  emissions from a latent Markov chain. Captures temporal persistence of
  regimes (markets stay in bull/bear for extended periods).
- **Markov-Switching Regression** (``fit_ms_regression``): When you want
  regime-dependent regression coefficients or intercepts. Useful for
  modeling time-varying factor exposures.
- **Gaussian Mixture** (``gaussian_mixture_regimes``): Quick classification
  without temporal structure. Good for labeling return distributions when
  you do not care about transition dynamics.

References:
    Hamilton, J. D. (1989). "A New Approach to the Economic Analysis of
    Nonstationary Time Series and the Business Cycle." *Econometrica*, 57(2).

    Ang, A. & Bekaert, G. (2002). "Regime Switches in Interest Rates."
    *Journal of Business & Economic Statistics*, 20(2).
"""

from __future__ import annotations

from typing import Any

import numpy as np
import pandas as pd

from wraquant.core.decorators import requires_extra


# ---------------------------------------------------------------------------
# Gaussian HMM
# ---------------------------------------------------------------------------


@requires_extra("regimes")
def fit_gaussian_hmm(
    returns: pd.Series | np.ndarray,
    n_states: int = 2,
    covariance_type: str = "full",
    n_init: int = 10,
    n_iter: int = 200,
    tol: float = 1e-4,
    random_state: int = 42,
) -> dict[str, Any]:
    """Fit a Gaussian Hidden Markov Model to financial return data.

    A Gaussian HMM assumes that observed returns are generated by a latent
    (hidden) Markov chain with *K* states. Each state *k* has its own
    Gaussian emission distribution N(mu_k, sigma_k). The model learns:

    1. **Transition matrix** A[i,j] = P(s_t = j | s_{t-1} = i)
    2. **Emission means** mu_k for each state
    3. **Emission covariances** Sigma_k for each state
    4. **Initial state distribution** pi_k = P(s_0 = k)

    The EM algorithm (Baum-Welch) is used for parameter estimation. Because
    EM can converge to local optima, multiple random restarts (``n_init``)
    are performed and the model with the highest log-likelihood is retained.

    **Typical interpretation for 2-state model on equity returns:**

    - **Low-volatility state** ("risk-on" / bull): Positive mean return,
      low standard deviation, high Sharpe ratio. Markets are calm.
    - **High-volatility state** ("risk-off" / crisis): Near-zero or negative
      mean return, high standard deviation. Markets are stressed.

    States are automatically re-ordered so that state 0 has the lowest
    volatility and state K-1 has the highest volatility. This ensures
    consistent labeling across runs.

    Parameters:
        returns: Return series (simple or log returns). If a pandas Series,
            NaN values are dropped and the index is preserved.
        n_states: Number of hidden states. Common choices are 2 (bull/bear)
            or 3 (bull/neutral/bear). Values above 5 risk overfitting.
        covariance_type: Type of covariance matrix. One of ``'full'``,
            ``'diag'``, ``'spherical'``, ``'tied'``.
        n_init: Number of random restarts for EM. The model with the
            highest log-likelihood is selected. More restarts reduce the
            chance of a poor local optimum.
        n_iter: Maximum number of EM iterations per restart.
        tol: Convergence threshold for EM.
        random_state: Base random seed for reproducibility.

    Returns:
        Dictionary with the following keys:

        - ``states`` (np.ndarray): Most likely state sequence (Viterbi),
          shape ``(T,)``, integers in ``[0, K-1]``.
        - ``state_probs`` (np.ndarray): Smoothed state probabilities,
          shape ``(T, K)``. Each row sums to 1.
        - ``transition_matrix`` (np.ndarray): Transition probability
          matrix, shape ``(K, K)``. Row *i* sums to 1.
        - ``means`` (np.ndarray): Emission means, shape ``(K,)``.
        - ``covariances`` (np.ndarray): Emission covariances,
          shape ``(K,)`` (variance per state for univariate data).
        - ``startprob`` (np.ndarray): Initial state distribution,
          shape ``(K,)``.
        - ``log_likelihood`` (float): Total log-likelihood of the data.
        - ``aic`` (float): Akaike Information Criterion.
        - ``bic`` (float): Bayesian Information Criterion.
        - ``n_states`` (int): Number of states.
        - ``steady_state`` (np.ndarray): Ergodic (stationary) distribution
          of the Markov chain, shape ``(K,)``.
        - ``avg_duration`` (np.ndarray): Expected duration in each state,
          ``1 / (1 - A[i,i])``, shape ``(K,)``.
        - ``model`` (GaussianHMM): The fitted hmmlearn model object.
        - ``index`` (pd.Index | None): Original index if input was a
          pandas Series.

    Example:
        >>> import numpy as np
        >>> import pandas as pd
        >>> rng = np.random.default_rng(42)
        >>> # Simulate 2-regime returns
        >>> low_vol = rng.normal(0.001, 0.008, 300)
        >>> high_vol = rng.normal(-0.002, 0.025, 200)
        >>> returns = pd.Series(np.concatenate([low_vol, high_vol]))
        >>> result = fit_gaussian_hmm(returns, n_states=2)
        >>> print(result['means'])        # Per-state means
        >>> print(result['transition_matrix'])  # Transition probabilities
        >>> print(result['steady_state'])  # Long-run regime probabilities

    Notes:
        The model uses hmmlearn's ``GaussianHMM``. For very long series
        (>10,000 observations), consider downsampling or using the
        variational Bayes variant.

    See Also:
        fit_ms_regression: Markov-switching regression with statsmodels.
        gaussian_mixture_regimes: GMM-based regime classification.
        regime_statistics: Compute per-regime financial statistics.
        regime_transition_analysis: Analyze regime transition dynamics.
    """
    from hmmlearn.hmm import GaussianHMM

    # Prepare data
    index = None
    if isinstance(returns, pd.Series):
        clean = returns.dropna()
        index = clean.index
        X = clean.values.reshape(-1, 1)
    else:
        X = np.asarray(returns, dtype=np.float64).flatten()
        mask = ~np.isnan(X)
        X = X[mask].reshape(-1, 1)

    T = len(X)

    # Fit with multiple restarts and keep the best
    best_model = None
    best_score = -np.inf

    for i in range(n_init):
        model = GaussianHMM(
            n_components=n_states,
            covariance_type=covariance_type,
            n_iter=n_iter,
            tol=tol,
            random_state=random_state + i,
        )
        try:
            model.fit(X)
            score = model.score(X)
            if score > best_score:
                best_score = score
                best_model = model
        except Exception:
            # EM can fail on degenerate initialisations; skip and try again
            continue

    if best_model is None:
        raise RuntimeError(
            f"All {n_init} EM restarts failed. Try different n_states or "
            "check that the data has sufficient variation."
        )

    model = best_model

    # Decode: Viterbi for most likely states, posterior for probabilities
    states = model.predict(X)
    state_probs = model.predict_proba(X)

    # Re-order states by ascending volatility for consistent labeling
    variances = _extract_variances(model.covars_, n_states, covariance_type)
    order = np.argsort(variances)

    # Remap states
    state_map = {int(old): new for new, old in enumerate(order)}
    states = np.array([state_map[int(s)] for s in states])
    state_probs = state_probs[:, order]

    means = model.means_.flatten()[order]
    covariances = variances[order]
    startprob = model.startprob_[order]

    # Reorder transition matrix
    transmat = model.transmat_[np.ix_(order, order)]

    # Information criteria
    # Number of free parameters for Gaussian HMM
    n_params = _count_hmm_params(n_states, covariance_type)
    log_likelihood = float(best_score)
    aic = 2 * n_params - 2 * log_likelihood
    bic = n_params * np.log(T) - 2 * log_likelihood

    # Steady-state (ergodic) distribution from transition matrix
    steady_state = _compute_steady_state(transmat)

    # Expected duration in each state: 1 / (1 - p_ii)
    self_transition = np.diag(transmat)
    avg_duration = 1.0 / np.maximum(1.0 - self_transition, 1e-10)

    return {
        "states": states,
        "state_probs": state_probs,
        "transition_matrix": transmat,
        "means": means,
        "covariances": covariances,
        "startprob": startprob,
        "log_likelihood": log_likelihood,
        "aic": aic,
        "bic": bic,
        "n_states": n_states,
        "steady_state": steady_state,
        "avg_duration": avg_duration,
        "model": model,
        "index": index,
    }


# ---------------------------------------------------------------------------
# Legacy wrapper (backward compatibility)
# ---------------------------------------------------------------------------


@requires_extra("regimes")
def fit_hmm(returns: pd.Series, n_states: int = 2) -> Any:
    """Fit a Gaussian HMM to return data (legacy interface).

    This is a thin compatibility wrapper around ``fit_gaussian_hmm``.
    New code should use ``fit_gaussian_hmm`` directly for richer output.

    Parameters:
        returns: Simple return series.
        n_states: Number of hidden states.

    Returns:
        Fitted ``hmmlearn.hmm.GaussianHMM`` model.

    See Also:
        fit_gaussian_hmm: Full-featured HMM fitting with rich output.
    """
    result = fit_gaussian_hmm(returns, n_states=n_states, n_init=5)
    return result["model"]


# ---------------------------------------------------------------------------
# Predict regime
# ---------------------------------------------------------------------------


def predict_regime(
    model: Any,
    returns: pd.Series | np.ndarray,
) -> dict[str, Any]:
    """Predict regime states and probabilities for new data.

    Given a fitted HMM (from ``fit_gaussian_hmm`` or hmmlearn directly),
    decode the most likely hidden state sequence and compute posterior
    state probabilities for new observations.

    Parameters:
        model: A fitted HMM model with ``predict`` and ``predict_proba``
            methods (e.g., from hmmlearn), **or** the dict returned by
            ``fit_gaussian_hmm`` (in which case the ``'model'`` key is
            used).
        returns: Return series to classify. NaN values are dropped.

    Returns:
        Dictionary with:

        - ``states`` (np.ndarray): Most likely state at each time step.
        - ``state_probs`` (np.ndarray): Posterior probabilities, shape
          ``(T, K)``.
        - ``index`` (pd.Index | None): Preserved index if input was a
          pandas Series.

    Example:
        >>> result = fit_gaussian_hmm(train_returns, n_states=2)
        >>> pred = predict_regime(result, test_returns)
        >>> print(pred['states'])
        >>> print(pred['state_probs'][:5])
    """
    # Accept dict output from fit_gaussian_hmm
    if isinstance(model, dict) and "model" in model:
        model = model["model"]

    index = None
    if isinstance(returns, pd.Series):
        clean = returns.dropna()
        index = clean.index
        X = clean.values.reshape(-1, 1)
    else:
        X = np.asarray(returns, dtype=np.float64).flatten()
        mask = ~np.isnan(X)
        X = X[mask].reshape(-1, 1)

    states = model.predict(X)
    state_probs = model.predict_proba(X)

    return {
        "states": states,
        "state_probs": state_probs,
        "index": index,
    }


# ---------------------------------------------------------------------------
# Markov-Switching Regression (statsmodels)
# ---------------------------------------------------------------------------


def fit_ms_regression(
    endog: pd.Series | np.ndarray,
    k_regimes: int = 2,
    trend: str = "c",
    switching_variance: bool = True,
    exog: pd.DataFrame | np.ndarray | None = None,
    n_iter: int = 200,
) -> dict[str, Any]:
    """Fit a Markov-switching regression model using statsmodels.

    This wraps ``statsmodels.tsa.regime_switching.MarkovRegression``,
    which estimates a linear regression where the intercept (and
    optionally variance) can switch between regimes according to a
    hidden Markov chain.

    **When to use:** When you want to model how the data-generating
    process changes across regimes, including regime-dependent means
    and volatilities. More interpretable than a raw HMM for economic
    modeling because you get regression coefficients per regime.

    The model:

    .. math::

        y_t = \\mu_{s_t} + x_t' \\beta_{s_t} + \\sigma_{s_t} \\epsilon_t

    where :math:`s_t \\in \\{0, 1, \\ldots, K-1\\}` follows a first-order
    Markov chain with transition matrix :math:`P`.

    Parameters:
        endog: Endogenous (dependent) variable. Typically a return series.
        k_regimes: Number of regimes (hidden states).
        trend: Trend specification for the mean equation.
            ``'c'`` (constant), ``'t'`` (linear trend), ``'ct'`` (both),
            ``'n'`` (no trend).
        switching_variance: If True, the variance switches across regimes.
            Almost always desirable for financial data.
        exog: Optional exogenous regressors, shape ``(T, p)``. The
            coefficients on these regressors are **not** switching by
            default (the intercept and variance switch).
        n_iter: Maximum number of EM iterations.

    Returns:
        Dictionary with:

        - ``smoothed_probs`` (np.ndarray): Smoothed regime probabilities,
          shape ``(T, K)``. ``smoothed_probs[:, k]`` is the probability
          of being in regime *k* at each time step given all data.
        - ``filtered_probs`` (np.ndarray): Filtered regime probabilities
          (using only past data), shape ``(T, K)``.
        - ``states`` (np.ndarray): Most likely state sequence (argmax
          of smoothed probabilities), shape ``(T,)``.
        - ``transition_matrix`` (np.ndarray): Transition matrix,
          shape ``(K, K)``.
        - ``regime_params`` (dict): Regime-specific parameters. Keys
          are ``'mean_0'``, ``'mean_1'``, ..., ``'sigma2_0'``, etc.
        - ``log_likelihood`` (float): Log-likelihood of the fitted model.
        - ``aic`` (float): Akaike Information Criterion.
        - ``bic`` (float): Bayesian Information Criterion.
        - ``summary`` (str): Text summary from statsmodels.
        - ``model_result`` (MarkovRegressionResults): The full
          statsmodels result object.

    Example:
        >>> import numpy as np, pandas as pd
        >>> rng = np.random.default_rng(0)
        >>> returns = pd.Series(np.concatenate([
        ...     rng.normal(0.001, 0.01, 200),
        ...     rng.normal(-0.002, 0.03, 200),
        ... ]))
        >>> result = fit_ms_regression(returns, k_regimes=2)
        >>> print(result['transition_matrix'])
        >>> print(result['regime_params'])

    Notes:
        Requires ``statsmodels >= 0.13``. The model uses Hamilton's
        (1989) filter for inference. Convergence can be sensitive to
        starting values.

    See Also:
        fit_gaussian_hmm: HMM using hmmlearn (more flexible emission
            distributions).
        regime_statistics: Compute financial statistics per regime.
    """
    from statsmodels.tsa.regime_switching.markov_regression import (
        MarkovRegression,
    )

    y = np.asarray(endog, dtype=np.float64).flatten()

    model = MarkovRegression(
        y,
        k_regimes=k_regimes,
        trend=trend,
        switching_variance=switching_variance,
        exog=exog,
    )
    result = model.fit(maxiter=n_iter, disp=False)

    # Extract regime-specific parameters
    regime_params: dict[str, float] = {}
    for k in range(k_regimes):
        regime_params[f"mean_{k}"] = float(result.params[k])
    if switching_variance:
        for k in range(k_regimes):
            regime_params[f"sigma2_{k}"] = float(
                result.params[k_regimes + k]
            )

    # Transition matrix from result
    transmat = np.array(result.regime_transition).T

    # statsmodels returns (K, T) shaped arrays; transpose to (T, K)
    raw_smoothed = np.array(result.smoothed_marginal_probabilities)
    raw_filtered = np.array(result.filtered_marginal_probabilities)

    # Ensure shape is (T, K) regardless of statsmodels version
    if raw_smoothed.shape[0] == k_regimes and raw_smoothed.shape[0] != raw_smoothed.shape[1]:
        smoothed_probs = raw_smoothed.T
    else:
        smoothed_probs = raw_smoothed
    if raw_filtered.shape[0] == k_regimes and raw_filtered.shape[0] != raw_filtered.shape[1]:
        filtered_probs = raw_filtered.T
    else:
        filtered_probs = raw_filtered

    states = np.argmax(smoothed_probs, axis=1)

    return {
        "smoothed_probs": smoothed_probs,
        "filtered_probs": filtered_probs,
        "states": states,
        "transition_matrix": transmat,
        "regime_params": regime_params,
        "log_likelihood": float(result.llf),
        "aic": float(result.aic),
        "bic": float(result.bic),
        "summary": str(result.summary()),
        "model_result": result,
    }


# ---------------------------------------------------------------------------
# Regime statistics
# ---------------------------------------------------------------------------


def regime_statistics(
    returns: pd.Series | np.ndarray,
    states: np.ndarray,
) -> pd.DataFrame:
    """Compute descriptive statistics for each detected regime.

    After fitting an HMM or GMM, this function summarizes the financial
    characteristics of each regime. Typical interpretation for a
    2-state model on equity returns:

    - **Regime 0** (low vol): "risk-on" or "bull market" -- positive
      mean return, low volatility, high Sharpe ratio.
    - **Regime 1** (high vol): "risk-off" or "crisis" -- negative
      or zero mean, high volatility, negative Sharpe.

    Parameters:
        returns: Return series aligned with ``states``. Can be a pandas
            Series or a numpy array.
        states: Integer regime labels (0, 1, ..., K-1), same length
            as ``returns``.

    Returns:
        pd.DataFrame with one row per regime and columns:
        ``mean``, ``std``, ``sharpe``, ``min``, ``max``,
        ``skewness``, ``kurtosis``, ``n_observations``,
        ``pct_time``, ``avg_duration``.

        - ``sharpe``: Annualized Sharpe ratio assuming 252 trading days.
        - ``avg_duration``: Mean consecutive time steps spent in the regime.

    Example:
        >>> result = fit_gaussian_hmm(returns, n_states=2)
        >>> stats = regime_statistics(returns, result['states'])
        >>> print(stats)
                    mean       std    sharpe  ...  avg_duration
        regime
        0       0.000523  0.008123  1.0223   ...          15.3
        1      -0.001842  0.024561 -1.1917   ...           7.8

    See Also:
        fit_gaussian_hmm: Fit HMM to obtain state assignments.
        regime_transition_analysis: Analyze transition dynamics.
    """
    r = np.asarray(returns, dtype=np.float64).flatten()
    s = np.asarray(states, dtype=int).flatten()

    if len(r) != len(s):
        raise ValueError(
            f"returns and states must have the same length, "
            f"got {len(r)} and {len(s)}."
        )

    total = len(r)
    unique_states = sorted(np.unique(s))
    records = []

    for state in unique_states:
        mask = s == state
        regime_r = r[mask]
        n_obs = int(mask.sum())

        mean_ret = float(np.mean(regime_r))
        std_ret = float(np.std(regime_r, ddof=1)) if n_obs > 1 else 0.0
        sharpe = (
            (mean_ret / std_ret * np.sqrt(252)) if std_ret > 1e-12 else 0.0
        )

        # Average consecutive duration in this regime
        avg_dur = _avg_regime_duration(s, state)

        records.append(
            {
                "regime": state,
                "mean": mean_ret,
                "std": std_ret,
                "sharpe": sharpe,
                "min": float(np.min(regime_r)),
                "max": float(np.max(regime_r)),
                "skewness": float(_skewness(regime_r)),
                "kurtosis": float(_kurtosis(regime_r)),
                "n_observations": n_obs,
                "pct_time": n_obs / total if total > 0 else 0.0,
                "avg_duration": avg_dur,
            }
        )

    return pd.DataFrame(records).set_index("regime")


# ---------------------------------------------------------------------------
# Regime transition analysis
# ---------------------------------------------------------------------------


def regime_transition_analysis(
    states: np.ndarray,
    transition_matrix: np.ndarray | None = None,
) -> dict[str, Any]:
    """Analyze regime transition dynamics.

    Computes empirical and model-based statistics about how regimes
    switch. Useful for understanding regime persistence and expected
    timing of regime changes.

    Parameters:
        states: Integer regime labels, shape ``(T,)``.
        transition_matrix: Model-estimated transition matrix, shape
            ``(K, K)``. If None, the empirical transition matrix is
            computed from ``states``.

    Returns:
        Dictionary with:

        - ``empirical_transition_matrix`` (np.ndarray): Transition
          counts normalised to probabilities, shape ``(K, K)``.
        - ``transition_matrix`` (np.ndarray): Model or empirical
          transition matrix used for analysis.
        - ``avg_duration`` (np.ndarray): Expected duration in each
          regime (time steps), ``1 / (1 - P[i,i])``.
        - ``steady_state`` (np.ndarray): Ergodic distribution from
          the transition matrix.
        - ``regime_counts`` (dict): Number of distinct "visits" to
          each regime.
        - ``regime_durations`` (dict): List of consecutive durations
          for each regime.
        - ``expected_return_time`` (np.ndarray): Expected number of
          steps to return to each regime from stationarity.

    Example:
        >>> result = fit_gaussian_hmm(returns, n_states=2)
        >>> analysis = regime_transition_analysis(
        ...     result['states'], result['transition_matrix']
        ... )
        >>> print(f"Bull market lasts ~{analysis['avg_duration'][0]:.0f} days")
        >>> print(f"Steady state: {analysis['steady_state']}")

    See Also:
        fit_gaussian_hmm: Fit HMM to obtain states and transition matrix.
        regime_statistics: Financial statistics per regime.
    """
    s = np.asarray(states, dtype=int).flatten()
    unique_states = sorted(np.unique(s))
    K = len(unique_states)

    # Empirical transition matrix
    emp_transmat = np.zeros((K, K))
    state_to_idx = {state: i for i, state in enumerate(unique_states)}
    for t in range(len(s) - 1):
        i = state_to_idx[s[t]]
        j = state_to_idx[s[t + 1]]
        emp_transmat[i, j] += 1

    # Normalise rows
    row_sums = emp_transmat.sum(axis=1, keepdims=True)
    row_sums = np.maximum(row_sums, 1e-10)
    emp_transmat = emp_transmat / row_sums

    # Use model transition matrix if provided, else empirical
    transmat = transition_matrix if transition_matrix is not None else emp_transmat

    # Expected duration: 1 / (1 - p_ii)
    self_transition = np.diag(transmat)
    avg_duration = 1.0 / np.maximum(1.0 - self_transition, 1e-10)

    # Steady state
    steady_state = _compute_steady_state(transmat)

    # Regime visits and durations
    regime_counts: dict[int, int] = {st: 0 for st in unique_states}
    regime_durations: dict[int, list[int]] = {st: [] for st in unique_states}
    if len(s) > 0:
        current_state = s[0]
        current_duration = 1
        regime_counts[current_state] = 1
        for t in range(1, len(s)):
            if s[t] == current_state:
                current_duration += 1
            else:
                regime_durations[current_state].append(current_duration)
                current_state = s[t]
                current_duration = 1
                regime_counts[current_state] += 1
        regime_durations[current_state].append(current_duration)

    # Expected return time: 1 / pi_i
    expected_return = np.zeros(K)
    for i in range(K):
        expected_return[i] = (
            1.0 / steady_state[i] if steady_state[i] > 1e-10 else np.inf
        )

    return {
        "empirical_transition_matrix": emp_transmat,
        "transition_matrix": transmat,
        "avg_duration": avg_duration,
        "steady_state": steady_state,
        "regime_counts": regime_counts,
        "regime_durations": regime_durations,
        "expected_return_time": expected_return,
    }


# ---------------------------------------------------------------------------
# Gaussian Mixture Regimes
# ---------------------------------------------------------------------------


def gaussian_mixture_regimes(
    returns: pd.Series | np.ndarray,
    n_components: int = 2,
    covariance_type: str = "full",
    n_init: int = 10,
    random_state: int = 42,
) -> dict[str, Any]:
    """Classify returns into regimes using a Gaussian Mixture Model.

    Unlike HMMs, GMMs do not model temporal dependence between states.
    Each observation is independently assigned to the most likely
    Gaussian component. This makes GMMs:

    - **Faster** to fit than HMMs.
    - **Simpler** to interpret (no transition dynamics).
    - **Less powerful** for capturing regime persistence.

    Good for quick regime labeling or as a baseline before fitting an HMM.

    The model:

    .. math::

        p(r_t) = \\sum_{k=1}^{K} \\pi_k \\, \\mathcal{N}(r_t; \\mu_k, \\Sigma_k)

    Parameters:
        returns: Return series. NaN values are dropped.
        n_components: Number of mixture components (regimes).
        covariance_type: Covariance type (``'full'``, ``'tied'``,
            ``'diag'``, ``'spherical'``).
        n_init: Number of random restarts.
        random_state: Random seed.

    Returns:
        Dictionary with:

        - ``states`` (np.ndarray): Component assignments, shape ``(T,)``.
        - ``state_probs`` (np.ndarray): Posterior probabilities, shape
          ``(T, K)``.
        - ``means`` (np.ndarray): Component means, shape ``(K,)``.
        - ``covariances`` (np.ndarray): Component variances, shape
          ``(K,)``.
        - ``weights`` (np.ndarray): Mixing proportions, shape ``(K,)``.
        - ``aic`` (float): AIC.
        - ``bic`` (float): BIC.
        - ``model`` (GaussianMixture): Fitted sklearn model.
        - ``index`` (pd.Index | None): Preserved index.

    Example:
        >>> result = gaussian_mixture_regimes(returns, n_components=2)
        >>> print(result['means'])   # Component means
        >>> print(result['weights']) # Mixing proportions
        >>> # Combine with regime_statistics for financial interpretation
        >>> stats = regime_statistics(returns, result['states'])

    See Also:
        fit_gaussian_hmm: HMM with temporal regime dynamics.
        regime_statistics: Per-regime financial statistics.
    """
    from sklearn.mixture import GaussianMixture

    index = None
    if isinstance(returns, pd.Series):
        clean = returns.dropna()
        index = clean.index
        X = clean.values.reshape(-1, 1)
    else:
        X = np.asarray(returns, dtype=np.float64).flatten()
        mask = ~np.isnan(X)
        X = X[mask].reshape(-1, 1)

    gmm = GaussianMixture(
        n_components=n_components,
        covariance_type=covariance_type,
        n_init=n_init,
        random_state=random_state,
    )
    gmm.fit(X)

    states = gmm.predict(X)
    state_probs = gmm.predict_proba(X)

    # Re-order by ascending variance
    variances = gmm.covariances_.flatten()[:n_components]
    order = np.argsort(variances)

    state_map = {int(old): new for new, old in enumerate(order)}
    states = np.array([state_map[int(s)] for s in states])
    state_probs = state_probs[:, order]

    means = gmm.means_.flatten()[order]
    covariances = variances[order]
    weights = gmm.weights_[order]

    return {
        "states": states,
        "state_probs": state_probs,
        "means": means,
        "covariances": covariances,
        "weights": weights,
        "aic": float(gmm.aic(X)),
        "bic": float(gmm.bic(X)),
        "model": gmm,
        "index": index,
    }


# ---------------------------------------------------------------------------
# Rolling Regime Probability
# ---------------------------------------------------------------------------


@requires_extra("regimes")
def rolling_regime_probability(
    returns: pd.Series,
    n_states: int = 2,
    window: int | None = None,
    min_window: int = 60,
    n_init: int = 5,
) -> pd.DataFrame:
    """Compute time-varying regime probabilities using rolling/expanding HMM.

    Fits a Gaussian HMM at each time step using either a rolling or
    expanding window, producing a time series of regime probabilities
    that adapts to new data. Useful for real-time regime monitoring.

    Parameters:
        returns: Return series.
        n_states: Number of hidden states.
        window: Rolling window size. If None, uses an expanding window
            (all data up to time *t*).
        min_window: Minimum number of observations required before
            fitting the first model.
        n_init: Number of EM restarts per window.

    Returns:
        pd.DataFrame with columns ``prob_0``, ``prob_1``, ..., ``prob_{K-1}``
        indexed by the return series index. Rows before ``min_window``
        are NaN.

    Example:
        >>> probs = rolling_regime_probability(returns, n_states=2, window=252)
        >>> probs.plot(title="Regime Probabilities Over Time")

    Notes:
        This is computationally expensive. For 1000 observations with
        ``window=252``, approximately 750 HMM fits are performed. Consider
        using a large ``window`` or expanding mode for efficiency.

    See Also:
        fit_gaussian_hmm: Single-shot HMM fitting.
    """
    clean = returns.dropna()
    T = len(clean)
    values = clean.values.reshape(-1, 1)

    prob_cols = [f"prob_{k}" for k in range(n_states)]
    result = pd.DataFrame(
        np.nan, index=clean.index, columns=prob_cols, dtype=float
    )

    for t in range(min_window, T):
        if window is not None:
            start = max(0, t - window)
        else:
            start = 0
        X_window = values[start : t + 1]

        try:
            hmm_result = fit_gaussian_hmm(
                X_window.flatten(),
                n_states=n_states,
                n_init=n_init,
                n_iter=100,
            )
            # Take the probability at the last time step
            last_probs = hmm_result["state_probs"][-1]
            result.iloc[t] = last_probs
        except Exception:
            # If EM fails for this window, leave as NaN
            pass

    return result


# ---------------------------------------------------------------------------
# Regime-Aware Portfolio
# ---------------------------------------------------------------------------


def regime_aware_portfolio(
    regime_probs: np.ndarray,
    regime_weights: np.ndarray,
) -> np.ndarray:
    """Compute blended portfolio weights using regime probabilities.

    Given the current probability of being in each regime and the
    optimal portfolio weights for each regime, compute a
    probability-weighted blend. This bridges regime detection
    (``regimes/``) with portfolio optimisation (``opt/``).

    The blended weight for asset *j* is:

    .. math::

        w_j = \\sum_{k=1}^{K} P(s_t = k) \\cdot w_j^{(k)}

    Parameters:
        regime_probs: Current regime probabilities, shape ``(K,)``.
            Must sum to 1.
        regime_weights: Optimal weights for each regime, shape
            ``(K, n_assets)``. Row *k* contains the weights for
            regime *k*.

    Returns:
        np.ndarray: Blended portfolio weights, shape ``(n_assets,)``.
        Sums to 1 if each row of ``regime_weights`` sums to 1.

    Example:
        >>> # 60% probability of bull, 40% probability of bear
        >>> probs = np.array([0.6, 0.4])
        >>> # Bull: 80% equity / 20% bonds; Bear: 30% equity / 70% bonds
        >>> weights = np.array([[0.8, 0.2], [0.3, 0.7]])
        >>> blended = regime_aware_portfolio(probs, weights)
        >>> print(blended)  # [0.6*0.8 + 0.4*0.3, 0.6*0.2 + 0.4*0.7]
        [0.6  0.4]

    See Also:
        fit_gaussian_hmm: Obtain regime probabilities.
        rolling_regime_probability: Time-varying regime probabilities.
    """
    probs = np.asarray(regime_probs, dtype=np.float64)
    weights = np.asarray(regime_weights, dtype=np.float64)

    if probs.ndim != 1:
        raise ValueError(f"regime_probs must be 1-D, got shape {probs.shape}")
    if weights.ndim != 2:
        raise ValueError(
            f"regime_weights must be 2-D, got shape {weights.shape}"
        )
    if probs.shape[0] != weights.shape[0]:
        raise ValueError(
            f"Number of regimes in probs ({probs.shape[0]}) and weights "
            f"({weights.shape[0]}) must match."
        )

    return probs @ weights


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _count_hmm_params(n_states: int, covariance_type: str) -> int:
    """Count free parameters in a univariate Gaussian HMM."""
    # Initial state: K - 1
    # Transition matrix: K * (K - 1)
    # Means: K
    # Covariances depend on type (univariate case)
    n_init_params = n_states - 1
    n_trans_params = n_states * (n_states - 1)
    n_mean_params = n_states
    if covariance_type in ("full", "diag", "diagonal", "spherical"):
        n_cov_params = n_states
    elif covariance_type == "tied":
        n_cov_params = 1
    else:
        n_cov_params = n_states
    return n_init_params + n_trans_params + n_mean_params + n_cov_params


def _extract_variances(
    covars: np.ndarray,
    n_states: int,
    covariance_type: str,
) -> np.ndarray:
    """Extract per-state variance from hmmlearn covars_ for univariate data.

    hmmlearn stores covariances differently depending on covariance_type:
    - full: (n_states, n_features, n_features)
    - diag: (n_states, n_features)
    - spherical: (n_states,)
    - tied: (n_features, n_features) -- same for all states

    Returns a flat 1-D float array of shape (n_states,).
    """
    if covariance_type == "spherical":
        result = np.asarray(covars, dtype=np.float64).flatten()[:n_states]
    elif covariance_type in ("diag", "diagonal"):
        # Shape (n_states, n_features) -- take first feature
        result = np.array(
            [float(covars[k].flatten()[0]) for k in range(n_states)]
        )
    elif covariance_type == "tied":
        # Same covariance for all states
        var = float(np.asarray(covars).flatten()[0])
        result = np.full(n_states, var)
    else:
        # full: (n_states, n_features, n_features) -- extract [0,0]
        result = np.array(
            [float(np.asarray(covars[k]).flatten()[0]) for k in range(n_states)]
        )
    return result


def _compute_steady_state(transmat: np.ndarray) -> np.ndarray:
    """Compute the ergodic (stationary) distribution of a transition matrix.

    Solves pi @ P = pi, sum(pi) = 1 using the eigenvalue method.
    """
    K = transmat.shape[0]
    # Find left eigenvector with eigenvalue 1
    eigenvalues, eigenvectors = np.linalg.eig(transmat.T)
    # Find the index of eigenvalue closest to 1
    idx = np.argmin(np.abs(eigenvalues - 1.0))
    steady = np.real(eigenvectors[:, idx])
    steady = np.abs(steady)  # Ensure non-negative
    total = steady.sum()
    if total > 0:
        steady /= total
    else:
        steady = np.ones(K) / K
    return steady


def _avg_regime_duration(states: np.ndarray, target_state: int) -> float:
    """Compute average consecutive duration in a particular regime."""
    durations: list[int] = []
    current_duration = 0
    for s in states:
        if s == target_state:
            current_duration += 1
        else:
            if current_duration > 0:
                durations.append(current_duration)
            current_duration = 0
    if current_duration > 0:
        durations.append(current_duration)
    return float(np.mean(durations)) if durations else 0.0


def _skewness(x: np.ndarray) -> float:
    """Compute sample skewness."""
    n = len(x)
    if n < 3:
        return 0.0
    m = np.mean(x)
    s = np.std(x, ddof=1)
    if s < 1e-12:
        return 0.0
    return float(np.mean(((x - m) / s) ** 3) * n / ((n - 1) * (n - 2) / n))


def _kurtosis(x: np.ndarray) -> float:
    """Compute sample excess kurtosis."""
    n = len(x)
    if n < 4:
        return 0.0
    m = np.mean(x)
    s = np.std(x, ddof=1)
    if s < 1e-12:
        return 0.0
    return float(np.mean(((x - m) / s) ** 4) - 3.0)
